services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back-end_destinify
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ROOT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - network2


  postgres:
    image: postgres
    container_name: container-postgres
    environment:
      POSTGRES_PASSWORD: ${ROOT_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres
    restart: always
    networks:
      - network2


networks:
  network2:
    driver: bridge


volumes:
  postgres_data:
