spring:
  application:
    name: api-viagem

  profiles:
    active: dev

  main:
    banner-mode: off
jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET}
    duration: 900000 # 15 minutos

  refresh-token:
    secret: ${JWT_REFRESH_SECRET}
    duration: 604800000 # 7 dias

app:
  cookie:
    secure: true


internal:
  api:
    key: ${INTERNAL_API_KEY}