spring:
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
    username: postgres.xduzjgpamammweblmalt
    password: postgres123&
    driver-class-name: org.postgresql.Driver



  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

admin:
  name: Administrador
  email: destinyfyone@gmail.com
